# Generated by Django 4.2.7 on 2023-11-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='days_of_attendance',
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('wednesday', 'wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, null=True),
        ),
    ]
